MindtermPartD/config/routes.rb
Rails.application.routes.draw do
  get 'show_date_time/display'

  resources :olumpicmedals
  get 'welcome/index'

  root 'welcome#index'

end

MindtermPartD/app/models/olumpicmedal.rb
class Olumpicmedal < ActiveRecord::Base
	validates :athlete_name, presence: { message: "required" }
	validates :country, presence: { message: "required" }
	validates :medal_type, :inclusion => { :in => ["gold", "silver", "bronze"] }
		
end

MindtermPartD/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

MindtermPartD/app/controllers/olumpicmedals_controller.rb
class OlumpicmedalsController < ApplicationController
  before_action :set_olumpicmedal, only: [:show, :edit, :update, :destroy]

  # GET /olumpicmedals
  # GET /olumpicmedals.json
  def index
    @olumpicmedals = Olumpicmedal.all
  end

  # GET /olumpicmedals/1
  # GET /olumpicmedals/1.json
  def show
  end

  # GET /olumpicmedals/new
  def new
    @olumpicmedal = Olumpicmedal.new
  end

  # GET /olumpicmedals/1/edit
  def edit
  end

  # POST /olumpicmedals
  # POST /olumpicmedals.json
  def create
    @olumpicmedal = Olumpicmedal.new(olumpicmedal_params)

    respond_to do |format|
      if @olumpicmedal.save
        format.html { redirect_to @olumpicmedal, notice: 'Olumpicmedal was successfully created.' }
        format.json { render :show, status: :created, location: @olumpicmedal }
      else
        format.html { render :new }
        format.json { render json: @olumpicmedal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /olumpicmedals/1
  # PATCH/PUT /olumpicmedals/1.json
  def update
    respond_to do |format|
      if @olumpicmedal.update(olumpicmedal_params)
        format.html { redirect_to @olumpicmedal, notice: 'Olumpicmedal was successfully updated.' }
        format.json { render :show, status: :ok, location: @olumpicmedal }
      else
        format.html { render :edit }
        format.json { render json: @olumpicmedal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /olumpicmedals/1
  # DELETE /olumpicmedals/1.json
  def destroy
    @olumpicmedal.destroy
    respond_to do |format|
      format.html { redirect_to olumpicmedals_url, notice: 'Olumpicmedal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_olumpicmedal
      @olumpicmedal = Olumpicmedal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def olumpicmedal_params
      params.require(:olumpicmedal).permit(:athlete_name, :event, :country, :medal_type, :event_date)
    end
end

MindtermPartD/app/controllers/show_date_time_controller.rb
class ShowDateTimeController < ApplicationController

	def display
    	@title = "Takehome Midterm -- Show Date and Time"
		t = Time.now
   	
    @date_time = t
    if t.hour >= 6 && t.hour <= 18 then
      @timeimg = "sun.png"
    else
      @timeimg = "moon.jpg"
    end
    @number = t.mon
    if t.mon == 1
      @monthname = "January"
      @monthimg = "jan.jpg"
    elsif t.mon == 2
      @monthname = "February"
      @monthimg = "feb.jpg"
    elsif t.mon == 3
      @monthname = "March"
      @monthimg = "mar.jpg"
    elsif t.mon == 4
      @monthname = "April"
      @monthimg = "apr.jpg"
    elsif t.mon == 5
      @monthname = "May"
      @monthimg = "may.jpg"
    elsif t.mon == 6
      @monthname = "June"
      @monthimg = "jun.jpg"
    elsif t.mon == 7
      @monthname = "July"
      @monthimg = "jul.jpg"
    elsif t.mon == 8
      @monthname = "August"
      @monthimg = "aug.jpg"
    elsif t.mon == 9
      @monthname = "September"
      @monthimg = "sep.jpg"
    elsif t.mon == 10
      @monthname = "October" 
      @monthimg = "oct.jpg"
    elsif t.mon == 11
      @monthname = "November" 
      @monthimg = "nov.jpg"
    elsif t.mon == 12
      @monthname = "December" 
      @monthimg = "dec.jpg"
    end



	end
end

MindtermPartD/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

MindtermPartD/app/helpers/application_helper.rb
module ApplicationHelper
end

MindtermPartD/app/helpers/olumpicmedals_helper.rb
module OlumpicmedalsHelper
end

MindtermPartD/app/helpers/show_date_time_helper.rb
module ShowDateTimeHelper
end

MindtermPartD/app/helpers/welcome_helper.rb
module WelcomeHelper
end

MindtermPartD/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MindtermPartC</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

MindtermPartD/app/views/olumpicmedals/_form.html.erb
<%= form_for(@olumpicmedal) do |f| %>
  <% if @olumpicmedal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@olumpicmedal.errors.count, "error") %> prohibited this olumpicmedal from being saved:</h2>

      <ul>
      <% @olumpicmedal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :athlete_name %><br>
    <%= f.text_field :athlete_name %>
  </div>
  <div class="field">
    <%= f.label :event %><br>
    <%= f.text_field :event %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :medal_type %><br>
    <%= f.text_field :medal_type %>
  </div>
  <div class="field">
    <%= f.label :event_date %><br>
    <%= f.datetime_select :event_date, :start_year => 2012, :end_year => 2012 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

MindtermPartD/app/views/olumpicmedals/edit.html.erb
<h1>Editing Olumpicmedal</h1>

<%= render 'form' %>

<%= link_to 'Show', @olumpicmedal %> |
<%= link_to 'Back', olumpicmedals_path %>

MindtermPartD/app/views/olumpicmedals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Olumpicmedals</h1>

<table>
  <thead>
    <tr>
      <th>Athlete name</th>
      <th>Event</th>
      <th>Country</th>
      <th>Medal type</th>
      <th>Event date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @olumpicmedals.each do |olumpicmedal| %>
      <tr>
        <td><%= olumpicmedal.athlete_name %></td>
        <td><%= olumpicmedal.event %></td>
        <td><%= olumpicmedal.country %></td>
        <td><%= olumpicmedal.medal_type %></td>
        <td><%= olumpicmedal.event_date %></td>
        <td><%= link_to 'Show', olumpicmedal %></td>
        <td><%= link_to 'Edit', edit_olumpicmedal_path(olumpicmedal) %></td>
        <td><%= link_to 'Destroy', olumpicmedal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Olumpicmedal', new_olumpicmedal_path %>

MindtermPartD/app/views/olumpicmedals/new.html.erb
<h1>New Olumpicmedal</h1>

<%= render 'form' %>

<%= link_to 'Back', olumpicmedals_path %>

MindtermPartD/app/views/olumpicmedals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Athlete name:</strong>
  <%= @olumpicmedal.athlete_name %>
</p>

<p>
  <strong>Event:</strong>
  <%= @olumpicmedal.event %>
</p>

<p>
  <strong>Country:</strong>
  <%= @olumpicmedal.country %>
</p>

<p>
  <strong>Medal type:</strong>
  <%= @olumpicmedal.medal_type %>
</p>

<p>
  <strong>Event date:</strong>
  <%= @olumpicmedal.event_date %>
</p>

<%= link_to 'Edit', edit_olumpicmedal_path(@olumpicmedal) %> |
<%= link_to 'Back', olumpicmedals_path %>

MindtermPartD/app/views/show_date_time/display.html.erb
<p>Date and Time:</p> <%= @datetime %><br>
<%= image_tag @timeimg, :class => "img" %>


<p>Month: </p><%= @monthname %><br />
<%= image_tag @monthimg, :class => "img" %>

----- Layout code in app/views/layouts/application.html.erb ------------------------

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>
<head>
<title><%= @title %>
<%= stylesheet_link_tag "application" %>

<body>
<h2><%= @title %></h2>
yield
</body>
</html>

MindtermPartD/app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>
<%= link_to "My Blog", olumpicmedals_path %>
<%= link_to "Show date Time", controller: "show_date_time", action: "display"%>